<?php namespace KevBaldwyn\ProjectEuler\Problems;

use KevBaldwyn\ProjectEuler\AbstractProblem;

class Problem2 extends AbstractProblem {

	public function name()
	{
		return '2';
	}

	public function title()
	{
		return 'Even Fibonacci numbers';
	}

	public function describe()
	{
		return 'Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
  1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
  By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.';
	}

	public function calculateAnswer()
	{
		$max      = 4000000;
		$evens    = [];
		$previous = [0, 1];
		$next     = 0;

		while($next < $max) {
			$numbers = array_slice($previous, -2, 2);
			$next    = array_sum($numbers);
			$previous[] = $next;
			if($next % 2 == 0) {
				$evens[] = $next;
			}
		}
		return array_sum($evens);
	}

}